name: pygeogrids
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=20.2.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - cartopy=0.18.0
  - certifi=2020.6.20
  - cffi=1.14.3
  - cfitsio=3.470
  - cftime=1.2.1
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cryptography=3.1.1
  - curl=7.71.1
  - cycler=0.10.0
  - expat=2.2.9
  - fiona=1.8.17
  - fontconfig=2.13.1
  - freetype=2.10.2
  - freexl=1.0.5
  - gdal=3.1.2
  - geopandas=0.8.1
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=67.1
  - idna=2.10
  - jpeg=9d
  - json-c=0.13.1
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lcms2=2.11
  - ld_impl_linux-64=2.35
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgdal=3.1.2
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libpq=12.3
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - munch=2.5.0
  - ncurses=6.2
  - netcdf4=1.5.4
  - numpy=1.19.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - owslib=0.20.0
  - pandas=1.1.2
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.2.3
  - pixman=0.38.0
  - poppler=0.89.0
  - poppler-data=0.4.9
  - postgresql=12.3
  - proj=7.1.0
  - pthread-stubs=0.4
  - pycparser=2.20
  - pyepsg=0.4.0
  - pykdtree=1.3.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyshp=2.1.2
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.24.0
  - rtree=0.9.4
  - scipy=1.5.2
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - sqlite=3.33.0
  - tbb=2020.2
  - tiledb=2.0.8
  - tk=8.6.10
  - tornado=6.0.4
  - tzcode=2020a
  - urllib3=1.25.10
  - wheel=0.35.1
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
